[package]
name = "dumbledore"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A ECS with async calls in mind"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

[dev-dependencies]
rand = "0.8.5"